const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={players:[],guides:[],book:[],cheats:[],sources:[],page:1,pageSize:80,batchFiles:[],batchRows:[],batchRawRows:[],guideTopic:'全部',expectedTotal:0,rosterSource:'',ocrReady:false,batchSort:'rank'};
const HEADER_ZH={"名前":"姓名","年齢":"年齡","成長":"成長型","投/打":"投／打","出身":"出身地","高校":"高中","大学":"大學","社会人":"社會人","タイプ":"投手類型","ランク":"Rank","体力":"體力","球速":"球速","球威":"球威","制球":"控球","精神":"精神","守備":"守備","捕球":"接球","肩力":"臂力","送球":"傳球","スライダー":"滑球","速スラ":"高速滑球","カットB":"卡特球","カーブ":"曲球","Sカーブ":"S曲球","ドロップ":"Drop曲球","シュート":"噴射球","速シュート":"高速噴射球","シンカー":"伸卡球","スクリュー":"螺旋球","速シンカー":"高速伸卡球","サークルC":"圈指變速","2シーム":"二縫線","Cアップ":"變速球","フォーク":"指叉球","SFF":"快速指叉","縦スラ":"縱滑球","パーム":"掌心球","ナックル":"蝴蝶球","スキル1":"技能1","スキル2":"技能2","スキル3":"技能3","モデル":"原型","右巧":"對右巧打","左巧":"對左巧打","長打":"長打","バント":"短打","選球眼":"選球眼","走力":"跑力","走塁":"跑壘","リード":"配球","捕手":"捕手","一塁":"一壘","二塁":"二壘","三塁":"三壘","遊撃":"游擊","外野":"外野","リーグ":"聯盟／地區","アカデミー":"學院"};
const BASE_COLS=['名前','ランク','年齢','成長','投/打','出身','タイプ','体力','球速','球威','制球','精神','守備','捕球','肩力','送球','右巧','左巧','長打','バント','選球眼','走力','走塁','スキル1','スキル2','スキル3','モデル'];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v??'').normalize('NFKC').toLowerCase().replace(/[\s　・·･,，。\.\/／()（）\-–—_:：;；'"「」『』【】\[\]]/g,'')}
function debounce(fn,ms=150){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
async function getJSON(url,opts={}){const r=await fetch(url,{cache:opts.cache||'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.json()}
const ROSTER_DB='yakyutsuku3-roster-v1',ROSTER_STORE='kv',ROSTER_KEY='players-3767';
function rosterDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB unavailable'));const q=indexedDB.open(ROSTER_DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(ROSTER_STORE);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error||new Error('IndexedDB open failed'))})}
async function rosterCacheGet(){try{const db=await rosterDB();return await new Promise((resolve,reject)=>{const tx=db.transaction(ROSTER_STORE,'readonly'),q=tx.objectStore(ROSTER_STORE).get(ROSTER_KEY);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)}).finally(()=>db.close())}catch(e){return null}}
async function rosterCachePut(players){if(!Array.isArray(players)||players.length<1000)return;try{const db=await rosterDB();await new Promise((resolve,reject)=>{const tx=db.transaction(ROSTER_STORE,'readwrite');tx.objectStore(ROSTER_STORE).put({players,updatedAt:Date.now()},ROSTER_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch(e){console.warn('roster cache',e)}}
function validRoster(x){return Array.isArray(x)&&x.length>=3500&&x.length<=4500&&x.every((p,i)=>i>20||p&&p['名前'])}
async function loadRoster(force=false){
  let netErr=null;
  try{const p=await getJSON(`./data/players.json${force?`?v=${Date.now()}`:''}`);if(!validRoster(p))throw new Error(`名冊筆數異常 ${Array.isArray(p)?p.length:'?'}`);await rosterCachePut(p);return{players:p,source:'網站名冊'}}catch(e){netErr=e}
  const cached=await rosterCacheGet();if(cached&&validRoster(cached.players))return{players:cached.players,source:'手機/瀏覽器快取'};
  const seed=await getJSON('./data/players-seed.json');return{players:seed,source:`Seed（完整名冊尚未取得：${netErr?.message||'offline'}）`};
}
function indexPlayers(players){return players.map((p,i)=>({...p,_uid:p._uid||`${p._slug||'p'}-${i}`,_search:norm(Object.entries(p).filter(([k])=>!k.startsWith('_')).map(([k,v])=>`${k} ${HEADER_ZH[k]||''} ${v}`).join(' ')+' '+(p._group||'')+' '+(p._position||''))}))}
async function loadData(forceRoster=false){
  const roster=await loadRoster(forceRoster);state.players=indexPlayers(roster.players);state.rosterSource=roster.source;
  [state.guides,state.book,state.cheats,state.sources]=await Promise.all([getJSON('./data/guides.json'),getJSON('./data/guide-book.json'),getJSON('./data/cheats.json'),getJSON('./data/sources.json')]);
  $('#dataStatus').textContent=`名冊 ${state.players.length.toLocaleString()} 人｜${state.rosterSource}｜攻略 ${state.guides.length.toLocaleString()} 筆`;
  renderPlayers();renderGuideTopics();renderGuides();renderCheats();renderSources();
}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${id}`));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='players')renderPlayers();if(id==='guides')renderGuides();if(id==='cheats')renderCheats()}
$$('.navbtn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function filteredPlayers(){const q=norm($('#playerQuery').value),g=$('#filterGroup').value,p=$('#filterPos').value,r=$('#filterRank').value;return state.players.filter(x=>(!q||x._search.includes(q))&&(!g||x._group===g)&&(!p||x._position===p)&&(!r||x['ランク']===r))}
function renderPlayers(){const list=filteredPlayers();const pages=Math.max(1,Math.ceil(list.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,rows=list.slice(start,start+state.pageSize);$('#playerCount').textContent=`${list.length.toLocaleString()} 人`;$('#pageInfo').textContent=`${state.page} / ${pages}`;$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=pages;const cols=BASE_COLS.filter(k=>rows.some(x=>x[k]!==undefined&&x[k]!==''));let h='<thead><tr>'+cols.map(k=>`<th>${esc(HEADER_ZH[k]||k)}</th>`).join('')+'<th>守位</th><th>分類</th></tr></thead><tbody>';for(const x of rows){h+='<tr>'+cols.map(k=>k==='名前'?`<td class="name" data-uid="${esc(x._uid)}">${esc(x[k])}</td>`:`<td class="${k==='ランク'?'rank':''}">${esc(x[k]||'—')}</td>`).join('')+`<td>${esc(x._position||'')}</td><td>${esc(x._group||'')}</td></tr>`}h+='</tbody>';$('#playerTable').innerHTML=h;$('#playerTable').querySelectorAll('[data-uid]').forEach(td=>td.onclick=()=>openPlayer(td.dataset.uid))}
$('#playerQuery').addEventListener('input',debounce(()=>{state.page=1;renderPlayers()}));['filterGroup','filterPos','filterRank'].forEach(id=>$('#'+id).onchange=()=>{state.page=1;renderPlayers()});$('#clearPlayer').onclick=()=>{$('#playerQuery').value='';$('#filterGroup').value='';$('#filterPos').value='';$('#filterRank').value='';state.page=1;renderPlayers()};$('#prevPage').onclick=()=>{state.page--;renderPlayers()};$('#nextPage').onclick=()=>{state.page++;renderPlayers()};
function openPlayer(uid){const p=state.players.find(x=>x._uid===uid);if(!p)return;const keys=Object.keys(p).filter(k=>!k.startsWith('_')&&k!=='Source URL'&&p[k]!==''&&p[k]!=null);$('#drawerBody').innerHTML=`<h2 class="detail-title">${esc(p['名前']||'選手資料')}</h2><div class="detail-grid">${keys.map(k=>`<div class="detail-item"><small>${esc(HEADER_ZH[k]||k)}${HEADER_ZH[k]&&HEADER_ZH[k]!==k?`｜${esc(k)}`:''}</small><b>${esc(p[k])}</b></div>`).join('')}</div>${p._source?`<p class="meta">來源：<a href="${esc(p._source)}" target="_blank" rel="noreferrer">${esc(p._source)}</a></p>`:''}`;$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false')}
$('#closeDrawer').onclick=$('.shade').onclick=()=>{$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true')};

function renderGuideTopics(){const topics=['全部',...new Set(state.guides.map(x=>x.sheet||x.group||'其他'))];$('#guideTopics').innerHTML=topics.slice(0,30).map(t=>`<button class="chip ${t===state.guideTopic?'active':''}" data-topic="${esc(t)}">${esc(t)}</button>`).join('');$('#guideTopics').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.guideTopic=b.dataset.topic;renderGuideTopics();renderGuides()})}
function renderGuides(){const q=norm($('#guideQuery').value);let rows=state.guides.filter(x=>(state.guideTopic==='全部'||(x.sheet||x.group||'其他')===state.guideTopic)&&(!q||norm(`${x.original||''} ${x.zh||''} ${x.sheet||''} ${x.group||''}`).includes(q)));rows=rows.slice(0,240);$('#guideResults').innerHTML=rows.map(x=>`<article class="card"><h3>${esc(x.sheet||x.group||'攻略')}</h3><p>${esc(x.zh||x.original||'')}</p><div class="meta">${esc(x.group||'')} ${x.row?`｜#${esc(x.row)}`:''}${x.source?`｜<a href="${esc(x.source)}" target="_blank" rel="noreferrer">來源</a>`:''}</div></article>`).join('')||'<div class="card">沒有符合的攻略。</div>'}
$('#guideQuery').addEventListener('input',debounce(renderGuides));$('#clearGuide').onclick=()=>{$('#guideQuery').value='';state.guideTopic='全部';renderGuideTopics();renderGuides()};
function flattenCheats(){const out=[];for(const ch of state.cheats){for(const sec of ch.sections||[]){if(sec.type==='table'){for(const row of sec.rows||[])out.push({chapter:ch.title,title:sec.title,text:(row||[]).join('｜'),row,headers:sec.headers,source:sec.source})}else for(const item of sec.items||[])out.push({chapter:ch.title,title:sec.title,text:item,source:sec.source})}}return out}
function renderCheats(){const q=norm($('#cheatQuery').value);const rows=flattenCheats().filter(x=>!q||norm(`${x.chapter} ${x.title} ${x.text}`).includes(q)).slice(0,260);$('#cheatResults').innerHTML=rows.map(x=>`<article class="card"><h3>${esc(x.title)}</h3>${x.row?`<table><tr>${x.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr><tr>${x.row.map(v=>`<td>${String(v).includes('\n')||/[0-9A-F]{8}/.test(String(v))?`<pre>${esc(v)}</pre>`:esc(v)}</td>`).join('')}</tr></table>`:`<p>${esc(x.text)}</p>`}${x.source?`<div class="meta"><a href="${esc(x.source)}" target="_blank" rel="noreferrer">來源</a></div>`:''}</article>`).join('')||'<div class="card">沒有符合的金手指資料。</div>'}
$('#cheatQuery').addEventListener('input',debounce(renderCheats));$('#clearCheat').onclick=()=>{$('#cheatQuery').value='';renderCheats()};
function renderSources(){$('#sourceList').innerHTML=state.sources.map(s=>`<article class="card"><h3><a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.name)}</a></h3><div class="source-role">${esc(s.role)}</div><div class="source-note">${esc(s.note)}</div><div class="meta">狀態：${esc(s.status)}｜優先級 ${esc(s.priority)}</div></article>`).join('')}
$('#refreshData').onclick=async()=>{const b=$('#refreshData');b.disabled=true;$('#dataStatus').textContent='更新完整名冊…';try{await loadData(true)}catch(e){$('#dataStatus').textContent='名冊更新失敗：'+e.message}finally{b.disabled=false}};

// --- 批次截圖找人：固定版面分列 → 本機同源 OCR → 3,767 人封閉候選 → 依選手 ID 去重。---
$('#batchFiles').onchange=e=>{state.batchFiles=[...e.target.files];state.batchRows=[];state.batchRawRows=[];state.expectedTotal=0;renderBatchPreview();renderBatchResults();$('#batchStatus').textContent=`已選 ${state.batchFiles.length} 張。`};
$('#clearBatch').onclick=()=>{state.batchFiles=[];state.batchRows=[];state.batchRawRows=[];state.expectedTotal=0;$('#batchFiles').value='';renderBatchPreview();renderBatchResults();$('#batchStatus').textContent='可一次選多張 OFFICE MENU 名單截圖。'};
function renderBatchPreview(){$('#batchPreview').innerHTML='';for(const f of state.batchFiles){const u=URL.createObjectURL(f),d=document.createElement('div');d.className='thumb';d.innerHTML=`<img src="${u}"><small>${esc(f.name)}</small>`;d.querySelector('img').onload=()=>setTimeout(()=>URL.revokeObjectURL(u),1000);$('#batchPreview').appendChild(d)}}
function loadImage(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('圖片解碼失敗'))};im.src=u})}
function rowCrops(img,fileName){const ratio=img.naturalWidth/img.naturalHeight;if(ratio<1.65)return[];const x0=.153,x1=.684,y0=.181,y1=.903,rows=11,rh=(y1-y0)/rows,out=[];for(let i=0;i<rows;i++){const y=y0+i*rh,c=document.createElement('canvas'),w=Math.round(img.naturalWidth*(x1-x0)),h=Math.round(img.naturalHeight*rh);c.width=w;c.height=h;c.getContext('2d',{willReadFrequently:true}).drawImage(img,Math.round(img.naturalWidth*x0),Math.round(img.naturalHeight*y),w,h,0,0,w,h);out.push({canvas:c,file:fileName,row:i+1})}return out}
function footerCrop(img,fileName){const c=document.createElement('canvas'),sx=Math.round(img.naturalWidth*.14),sy=Math.round(img.naturalHeight*.895),sw=Math.round(img.naturalWidth*.76),sh=Math.max(1,img.naturalHeight-sy);c.width=sw;c.height=sh;c.getContext('2d',{willReadFrequently:true}).drawImage(img,sx,sy,sw,sh,0,0,sw,sh);return{canvas:c,file:fileName}}
function grayPixels(src){const g=src.getContext('2d',{willReadFrequently:true}),d=g.getImageData(0,0,src.width,src.height),a=new Uint8Array(src.width*src.height);for(let i=0,j=0;i<d.data.length;i+=4,j++)a[j]=Math.round(d.data[i]*.299+d.data[i+1]*.587+d.data[i+2]*.114);return a}
function binaryCanvas(src,threshold=125,{cropName=false,scale=3}={}){let sx=0,sw=src.width;if(cropName){sx=Math.round(src.width*.115);sw=Math.round(src.width*.49)}const tmp=document.createElement('canvas');tmp.width=sw;tmp.height=src.height;tmp.getContext('2d',{willReadFrequently:true}).drawImage(src,sx,0,sw,src.height,0,0,sw,src.height);const g=tmp.getContext('2d',{willReadFrequently:true}),id=g.getImageData(0,0,sw,tmp.height),gray=new Uint8Array(sw*tmp.height);for(let i=0,j=0;i<id.data.length;i+=4,j++)gray[j]=Math.round(id.data[i]*.299+id.data[i+1]*.587+id.data[i+2]*.114);
  // 遊戲姓名欄中間有固定白色方塊。它不是文字；若不移除會被 OCR 當成一個假漢字。
  if(!cropName){const occ=new Float32Array(sw);for(let x=0;x<sw;x++){let n=0;for(let y=0;y<tmp.height;y++)if(gray[y*sw+x]>185)n++;occ[x]=n/tmp.height}let best=null,st=-1;for(let x=0;x<=sw;x++){const ok=x<sw&&x>sw*.18&&x<sw*.45&&occ[x]>.65;if(ok&&st<0)st=x;if((!ok||x===sw)&&st>=0){const en=x,w=en-st;if(w>=8&&(!best||w>best[2]))best=[st,en,w];st=-1}}if(best){const [a,b]=best;let sum=0,n=0;for(let y=0;y<tmp.height;y++)for(let x=Math.max(0,a-9);x<a;x++){sum+=gray[y*sw+x];n++}const bg=n?Math.round(sum/n):75;for(let y=0;y<tmp.height;y++)for(let x=Math.max(0,a-3);x<Math.min(sw,b+3);x++)gray[y*sw+x]=bg}}
  const out=document.createElement('canvas');out.width=sw*scale;out.height=tmp.height*scale;const small=document.createElement('canvas');small.width=sw;small.height=tmp.height;const sg=small.getContext('2d'),od=sg.createImageData(sw,tmp.height);for(let j=0;j<gray.length;j++){const v=gray[j]>threshold?0:255,i=j*4;od.data[i]=od.data[i+1]=od.data[i+2]=v;od.data[i+3]=255}sg.putImageData(od,0,0);const og=out.getContext('2d');og.imageSmoothingEnabled=true;og.drawImage(small,0,0,out.width,out.height);return out}
function binaryRegion(src,rx0,rx1,threshold=128,scale=5){const sx=Math.max(0,Math.round(src.width*rx0)),ex=Math.min(src.width,Math.round(src.width*rx1)),sw=Math.max(1,ex-sx),tmp=document.createElement('canvas');tmp.width=sw;tmp.height=src.height;tmp.getContext('2d',{willReadFrequently:true}).drawImage(src,sx,0,sw,src.height,0,0,sw,src.height);const g=tmp.getContext('2d',{willReadFrequently:true}),id=g.getImageData(0,0,sw,tmp.height),gray=new Uint8Array(sw*tmp.height);let sum=0;for(let i=0,j=0;i<id.data.length;i+=4,j++){gray[j]=Math.round(id.data[i]*.299+id.data[i+1]*.587+id.data[i+2]*.114);sum+=gray[j]}const avg=sum/Math.max(1,gray.length),th=Math.max(95,Math.min(165,threshold+(avg-120)*.18)),small=document.createElement('canvas');small.width=sw;small.height=tmp.height;const sg=small.getContext('2d'),od=sg.createImageData(sw,tmp.height);for(let j=0;j<gray.length;j++){const v=gray[j]>th?0:255,i=j*4;od.data[i]=od.data[i+1]=od.data[i+2]=v;od.data[i+3]=255}sg.putImageData(od,0,0);const out=document.createElement('canvas');out.width=sw*scale;out.height=tmp.height*scale;const og=out.getContext('2d');og.imageSmoothingEnabled=false;og.drawImage(small,0,0,out.width,out.height);return out}
function ocrNamePart(s){return cleanOCR(s).replace(/[^\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}々ヶヵーA-Za-z]/gu,'').trim()}
function splitPlayerName(v){const a=String(v||'').trim().split(/\s+/).filter(Boolean);return{surname:a[0]||'',given:a.slice(1).join('')}}
function detectNameSeparator(canvas){const g=canvas.getContext('2d',{willReadFrequently:true}),id=g.getImageData(0,0,canvas.width,canvas.height).data,x0=Math.floor(canvas.width*.18),x1=Math.floor(canvas.width*.44),y0=Math.floor(canvas.height*.16),y1=Math.floor(canvas.height*.84),occ=[];for(let x=x0;x<x1;x++){let n=0;for(let y=y0;y<y1;y++){const i=(y*canvas.width+x)*4,l=id[i]*.299+id[i+1]*.587+id[i+2]*.114;if(l>178)n++}occ.push(n/Math.max(1,y1-y0))}let best=null,st=-1;for(let i=0;i<=occ.length;i++){const ok=i<occ.length&&occ[i]>.46;if(ok&&st<0)st=i;if((!ok||i===occ.length)&&st>=0){const en=i,w=en-st;if(w>=4&&(!best||w>best.w))best={a:x0+st,b:x0+en,w};st=-1}}return best?{left:best.a/canvas.width,right:best.b/canvas.width}:{left:.285,right:.325}}
function batchUserWords(){if(state._batchUserWords)return state._batchUserWords;const out=new Set();for(const p of state.players){const n=String(p['名前']||'');if(/[ぁ-ゖァ-ヺー]/.test(n))continue;const q=splitPlayerName(n);if(q.surname)out.add(q.surname);if(q.given)out.add(q.given);if(q.surname&&q.given)out.add(q.surname+q.given)}state._batchUserWords=[...out].join('\n');return state._batchUserWords}
function batchKanjiWhitelist(){if(state._batchKanjiWhitelist)return state._batchKanjiWhitelist;const chars=new Set();for(const p of state.players)for(const ch of String(p['名前']||''))if(/[\p{Script=Han}々ヶヵ]/u.test(ch))chars.add(ch);state._batchKanjiWhitelist=[...chars].join('');return state._batchKanjiWhitelist}
async function recognizeFixedParts(worker,canvas,threshold=125){const sep=detectNameSeparator(canvas),wl=batchKanjiWhitelist();try{await worker.setParameters({tessedit_pageseg_mode:'8',tessedit_char_whitelist:wl,user_words_file:'yt3-user-words.txt'})}catch(e){}const a=await recognizeText(worker,binaryRegion(canvas,.115,Math.max(.18,sep.left-.008),threshold,6)),b=await recognizeText(worker,binaryRegion(canvas,Math.min(.50,sep.right+.008),.575,threshold,6));try{await worker.setParameters({tessedit_pageseg_mode:'10',tessedit_char_whitelist:'投捕一二三遊外'})}catch(e){}const ps=await recognizeText(worker,binaryRegion(canvas,.012,.105,threshold,5));try{await worker.setParameters({tessedit_pageseg_mode:'7',tessedit_char_whitelist:'0123456789歳才'})}catch(e){}const ag=await recognizeText(worker,binaryRegion(canvas,.60,.75,threshold,4));try{await worker.setParameters({tessedit_pageseg_mode:'7',tessedit_char_whitelist:'右左両/／'})}catch(e){}const hd=await recognizeText(worker,binaryRegion(canvas,.78,.985,threshold,4));try{await worker.setParameters({tessedit_pageseg_mode:'7',tessedit_char_whitelist:''})}catch(e){}const age=(cleanOCR(ag.text).match(/(18|19|20|21|22|23|24)/)||[])[1]||'',ht=cleanOCR(hd.text).replace(/石/g,'右').replace(/布/g,'右').replace(/[|｜]/g,'/'),hm=ht.match(/([右左])\s*[\/／]\s*([右左両])/),pos=(cleanOCR(ps.text).match(/[投捕一二三遊外]/)||[])[0]||'';return{surname:ocrNamePart(a.text),given:ocrNamePart(b.text),age,hand:hm?`${hm[1]}/${hm[2]}`:'',pos,confidence:Math.round((a.confidence+b.confidence+ps.confidence+ag.confidence+hd.confidence)/5),raw:`${ps.text}｜${a.text}｜□｜${b.text}｜${ag.text}｜${hd.text}`,separator:sep}}
function dhash(canvas){const c=document.createElement('canvas');c.width=17;c.height=8;const g=c.getContext('2d',{willReadFrequently:true});g.filter='grayscale(1) contrast(1.7)';g.drawImage(canvas,0,0,17,8);const d=g.getImageData(0,0,17,8).data,bits=[];for(let y=0;y<8;y++)for(let x=0;x<16;x++){const a=d[(y*17+x)*4],b=d[(y*17+x+1)*4];bits.push(a>b?1:0)}return bits}
function ham(a,b){let n=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])n++;return n}
async function ensureLocalOCR(){if(window.Tesseract){state.ocrReady=true;return true}return new Promise(resolve=>{const old=document.querySelector('script[data-yt3-ocr]');if(old)old.remove();const s=document.createElement('script');s.dataset.yt3Ocr='1';s.src='./vendor/tesseract/tesseract.min.js';s.onload=()=>{state.ocrReady=!!window.Tesseract;resolve(state.ocrReady)};s.onerror=()=>resolve(false);document.head.appendChild(s)})}
function cleanOCR(s){return String(s||'').normalize('NFKC').replace(/[|｜]/g,' ').replace(/\s+/g,' ').trim()}
function lev(a,b){a=norm(a);b=norm(b);const m=a.length,n=b.length,d=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)d[i][0]=i;for(let j=0;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[m][n]}
function ocrNameOnly(s){let t=cleanOCR(s).replace(/[0-9A-Za-z]/g,' ').replace(/[／/]/g,' ').replace(/[歳才]/g,' ').replace(/\s+/g,' ').trim();let toks=t.split(' ').filter(Boolean);while(toks.length>2&&['投','捕','一','二','三','遊','外','右','左','両'].includes(toks[0]))toks.shift();return toks.length>=2?toks.slice(-2).join(' '):(toks[0]||t)}
function parseRowText(text,altName=''){const t=cleanOCR(text),age=(t.match(/(18|19|20|21|22|23|24)\s*[歳才誠読講計寺武成]?/)||[])[1]||'',hm=t.match(/([右左])\s*[\/／]\s*([右左両])/),hand=hm?`${hm[1]}/${hm[2]}`:'';let pos='';const leadTokens=t.split(/\s+/).slice(0,4);for(const k of ['投','捕','一','二','三','遊','外'])if(leadTokens.includes(k)){pos=k;break}let before=t;if(age){const ix=t.indexOf(age);if(ix>0)before=t.slice(0,ix)}before=before.replace(/[0-9A-Za-z]/g,' ').replace(/[|｜\/／]/g,' ').replace(/\s+/g,' ').trim();let name=ocrNameOnly(altName||before);return{text:t,age,hand,pos,name,names:[...new Set([name,ocrNameOnly(before),ocrNameOnly(altName)].filter(Boolean))]}}
const POSMAP={投:'投手',捕:'捕手',一:'一壘手',二:'二壘手',三:'三壘手',遊:'游擊手',外:'外野手'};
function nameSimilarity(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;const d=lev(a,b),ed=1-d/Math.max(a.length,b.length,1);let common=0,bb=[...b];for(const ch of a){const i=bb.indexOf(ch);if(i>=0){common++;bb.splice(i,1)}}const bag=2*common/(a.length+b.length);return Math.max(0,ed*.72+bag*.28)}
function candidateMatch(parsed){const names=parsed.names?.length?parsed.names:[parsed.name],surnames=[...new Set([parsed.surname,...(parsed.surnames||[])].filter(Boolean))],givens=[...new Set([parsed.given,...(parsed.givens||[])].filter(Boolean))],kanjiOnly=state.batchFiles.length>0;let pool=kanjiOnly?state.players.filter(p=>!/[ぁ-ゖァ-ヺー]/.test(String(p['名前']||''))):state.players;if(!pool.length)pool=state.players;const gates=[];if(parsed.pos)gates.push(p=>p._position===POSMAP[parsed.pos]);if(parsed.age)gates.push(p=>String(p['年齢']||'')===parsed.age);if(parsed.hand)gates.push(p=>String(p['投/打']||'').replace('／','/')===parsed.hand);for(const gate of gates){const narrowed=pool.filter(gate);if(narrowed.length>=1)pool=narrowed}const scored=pool.map(p=>{const pn=p['名前']||'',parts=splitPlayerName(pn),full=Math.max(...names.map(n=>nameSimilarity(n,pn)),0),sur=surnames.length?Math.max(...surnames.map(n=>nameSimilarity(n,parts.surname)),0):0,giv=givens.length?Math.max(...givens.map(n=>nameSimilarity(n,parts.given)),0):0,den=(surnames.length?0.54:0)+(givens.length?0.46:0)||1,part=(sur*.54+giv*.46)/den,ns=Math.max(full,part);let score=ns*.70,meta=0;if(parsed.age&&String(p['年齢']||'')===parsed.age){score+=.12;meta++}if(parsed.hand&&String(p['投/打']||'').replace('／','/')===parsed.hand){score+=.11;meta++}if(parsed.pos&&p._position===POSMAP[parsed.pos]){score+=.07;meta++}const sl=surnames[0]?.length||0,gl=givens[0]?.length||0;if(sl&&Math.abs([...parts.surname].length-[...surnames[0]].length)>1)score-=.06;if(gl&&Math.abs([...parts.given].length-[...givens[0]].length)>1)score-=.06;return{p,score,nameScore:ns,fullScore:full,surnameScore:sur,givenScore:giv,meta}}).sort((a,b)=>b.score-a.score),best=scored[0],second=scored[1];if(!best)return{match:null,candidates:[]};const margin=best.score-(second?.score||0),splitStrong=(surnames.length&&givens.length&&best.surnameScore>=.70&&best.givenScore>=.60),metaStrong=best.meta>=2&&pool.length<=80;const accept=(best.nameScore>=.88&&margin>=.02)||(splitStrong&&best.meta>=1&&margin>=.018)||(metaStrong&&best.nameScore>=.54&&margin>=.018)||(best.meta>=3&&best.nameScore>=.48&&margin>=.015);return{match:accept?best:null,candidates:scored.slice(0,12),margin}}
function parseExpectedTotal(text){const t=cleanOCR(text);let m=t.match(/(?:合計|含計|会計|馬軒)[^0-9]{0,8}(\d{2,3})\s*人/);if(m)return +m[1];const nums=[...t.matchAll(/(\d{2,3})\s*人/g)].map(x=>+x[1]).filter(n=>n>=20&&n<=200);return nums.length?Math.max(...nums):0}
function mergeEvidence(a,b){const pa=a.parsed||{},pb=b.parsed||{},parsed={...pa,names:[...new Set([...(pa.names||[]),...(pb.names||[])].filter(Boolean))],surnames:[...new Set([pa.surname,...(pa.surnames||[]),pb.surname,...(pb.surnames||[])].filter(Boolean))],givens:[...new Set([pa.given,...(pa.givens||[]),pb.given,...(pb.givens||[])].filter(Boolean))]};if(!parsed.age)parsed.age=pb.age;if(!parsed.hand)parsed.hand=pb.hand;if(!parsed.pos)parsed.pos=pb.pos;const cm=candidateMatch(parsed),keep=(b.ocrConfidence||0)>(a.ocrConfidence||0)?b:a;return{...keep,parsed,raw:[a.raw,b.raw].filter(Boolean).join(' || '),ocrConfidence:Math.max(a.ocrConfidence||0,b.ocrConfidence||0),match:cm.match,candidates:cm.candidates,score:cm.match?.score||cm.candidates?.[0]?.score||0,firstIndex:Math.min(a.firstIndex??9999,b.firstIndex??9999),sources:[...(a.sources||[`${a.file}#${a.row}`]),...(b.sources||[`${b.file}#${b.row}`])]}}
function consolidateRows(raw,expected=0){const clusters=[];for(const r0 of raw){const r={...r0},h=r.hash||dhash(binaryRegion(r.canvas,.105,.585,126,2));r.hash=h;let idx=-1,best=999;for(let i=0;i<clusters.length;i++){const d=ham(h,clusters[i].hash);if(d<best&&d<=7){best=d;idx=i}}if(idx>=0)clusters[idx]=mergeEvidence(clusters[idx],r);else clusters.push({...r,sources:[`${r.file}#${r.row}`]})}clusters.sort((a,b)=>(a.firstIndex??9999)-(b.firstIndex??9999));let out=clusters;if(expected&&out.length>expected)out=[...out].sort((a,b)=>(b.match?.score||b.candidates?.[0]?.score||0)-(a.match?.score||a.candidates?.[0]?.score||0)).slice(0,expected).sort((a,b)=>(a.firstIndex??9999)-(b.firstIndex??9999));return out}
function resolveUniqueCandidates(rows){for(const r of rows)r.resolved=null;const used=new Set(rows.filter(r=>r.match?.p?._uid).map(r=>r.match.p._uid)),pending=rows.filter(r=>!r.match);for(let guard=0;guard<rows.length;guard++){let pick=null;for(const r of pending){if(r.resolved)continue;const av=(r.candidates||[]).filter(x=>!used.has(x.p._uid));if(!av.length)continue;const a=av[0],b=av[1],gap=a.score-(b?.score||0),quality=a.score+gap*.45+a.meta*.015;if(a.score<.49)continue;if(!pick||quality>pick.quality)pick={r,a,gap,quality}}if(!pick)break;pick.r.resolved=pick.a;pick.r.status=pick.r.status==='確認'?'確認':'推定';used.add(pick.a.p._uid)}return rows}
function batchDisplayPlayer(r){return r.match?.p||r.resolved?.p||r.candidates?.[0]?.p||null}
function sortBatchRows(rows){const out=[...rows],rank={S:0,A:1,B:2,C:3,D:4};if(state.batchSort==='screen')return out.sort((a,b)=>(a.firstIndex??9999)-(b.firstIndex??9999));if(state.batchSort==='name')return out.sort((a,b)=>String(batchDisplayPlayer(a)?.['名前']||'').localeCompare(String(batchDisplayPlayer(b)?.['名前']||''),'ja'));if(state.batchSort==='confidence')return out.sort((a,b)=>(b.match?.score||b.resolved?.score||b.candidates?.[0]?.score||0)-(a.match?.score||a.resolved?.score||a.candidates?.[0]?.score||0));return out.sort((a,b)=>((rank[batchDisplayPlayer(a)?.['ランク']]??9)-(rank[batchDisplayPlayer(b)?.['ランク']]??9))||String(batchDisplayPlayer(a)?.['名前']||'').localeCompare(String(batchDisplayPlayer(b)?.['名前']||''),'ja'))}
async function recognizeText(worker,canvas){const r=await worker.recognize(canvas);return{text:cleanOCR(r?.data?.text||''),confidence:Number(r?.data?.confidence||0)}}
async function runBatch(){if(!state.batchFiles.length){alert('請先選擇截圖。');return}if(state.players.length<1000){$('#batchStatus').textContent='完整名冊尚未載入，請先到「資料」按更新名冊。';return}$('#runBatch').disabled=true;let worker=null;try{const screens=[],all=[];$('#batchStatus').textContent='讀取截圖並切成固定名單列…';for(const f of state.batchFiles){const im=await loadImage(f),rows=rowCrops(im,f.name);screens.push({file:f.name,footer:footerCrop(im,f.name)});all.push(...rows)}state.batchRawRows=all.map((r,i)=>({...r,firstIndex:i,status:'待辨識',raw:'',parsed:null,match:null,candidates:[],ocrConfidence:0,score:0}));state.batchRows=[];renderBatchResults();$('#batchStatus').textContent=`已切出 ${all.length} 個畫面列；載入手機/桌機共用本機引擎…`;const ok=await ensureLocalOCR();if(!ok)throw new Error('本機辨識引擎檔案未載入；請重新整理網站後再試');worker=await Tesseract.createWorker('jpn',1,{workerPath:'./vendor/tesseract/worker.min.js',corePath:'./vendor/tesseract-core',langPath:'./vendor/lang',logger:m=>{if(m.status==='loading tesseract core'||m.status==='loading language traineddata')$('#batchStatus').textContent='載入本機日文辨識資料…'}});try{await worker.writeText('yt3-user-words.txt',batchUserWords());await worker.setParameters({tessedit_pageseg_mode:'7',preserve_interword_spaces:'1',user_words_file:'yt3-user-words.txt'})}catch(e){console.warn('player dictionary',e)}
  // 先讀頁尾的「合計 xx 人」；只作結果上限，不會把部分截圖強行補到總人數。
  let totals=[];for(const s of screens){try{const f=await recognizeText(worker,binaryCanvas(s.footer.canvas,120,{scale:3})),n=parseExpectedTotal(f.text);if(n)totals.push(n)}catch(e){}}state.expectedTotal=totals.length?Math.max(...totals):0;
  for(let i=0;i<state.batchRawRows.length;i++){const row=state.batchRawRows[i];$('#batchStatus').textContent=`辨識 ${i+1}/${state.batchRawRows.length}${state.expectedTotal?`｜名單上限 ${state.expectedTotal}`:''}`;try{let a=await recognizeText(worker,binaryCanvas(row.canvas,125,{scale:3}));let parsed=parseRowText(a.text),cm=candidateMatch(parsed);row.raw=a.text;row.ocrConfidence=a.confidence;row.parsed=parsed;row.match=cm.match;row.candidates=cm.candidates;row.score=cm.match?.score||cm.candidates?.[0]?.score||0;
      if(!row.match){const np=await recognizeFixedParts(worker,row.canvas,125);parsed=parseRowText(a.text);parsed.surname=np.surname;parsed.given=np.given;parsed.age=np.age||parsed.age;parsed.hand=np.hand||parsed.hand;parsed.pos=np.pos||parsed.pos;parsed.names=[...new Set([...(parsed.names||[]),`${np.surname} ${np.given}`.trim()].filter(Boolean))];cm=candidateMatch(parsed);row.raw=`${a.text}｜固定欄:${np.raw}`;row.ocrConfidence=Math.max(a.confidence,np.confidence);row.parsed=parsed;row.match=cm.match;row.candidates=cm.candidates;row.score=cm.match?.score||cm.candidates?.[0]?.score||0}
      if(!row.match&&row.candidates?.[0]?.nameScore<.68){const np2=await recognizeFixedParts(worker,row.canvas,145);parsed={...row.parsed,surname:np2.surname||row.parsed?.surname,given:np2.given||row.parsed?.given,age:np2.age||row.parsed?.age,hand:np2.hand||row.parsed?.hand,pos:np2.pos||row.parsed?.pos};parsed.names=[...new Set([...(parsed.names||[]),`${np2.surname} ${np2.given}`.trim()].filter(Boolean))];cm=candidateMatch(parsed);row.raw=`${row.raw}｜固定欄補辨:${np2.raw}`;row.ocrConfidence=Math.max(row.ocrConfidence,np2.confidence);row.parsed=parsed;row.match=cm.match;row.candidates=cm.candidates;row.score=cm.match?.score||cm.candidates?.[0]?.score||0}
      row.status=row.match?'確認':'候選';}catch(e){row.status='失敗';row.raw=String(e.message||e)}if(i%4===0){state.batchRows=consolidateRows(state.batchRawRows.slice(0,i+1),0);renderBatchResults()}}
  state.batchRows=resolveUniqueCandidates(consolidateRows(state.batchRawRows,state.expectedTotal));const matched=state.batchRows.filter(r=>r.match).length,inferred=state.batchRows.filter(r=>!r.match&&r.resolved).length;$('#batchStatus').textContent=`完成：${state.batchRows.length} 人${state.expectedTotal?`／畫面名單上限 ${state.expectedTotal}`:''}；確認 ${matched}，推定 ${inferred}，候選 ${state.batchRows.length-matched-inferred}。`;renderBatchResults();
 }catch(e){console.error(e);$('#batchStatus').textContent='批次找人失敗：'+(e.message||e)}finally{if(worker)try{await worker.terminate()}catch(e){}$('#runBatch').disabled=false}}
$('#runBatch').onclick=runBatch;
function renderBatchResults(){const rows=sortBatchRows(state.batchRows),matched=state.batchRows.filter(r=>r.match).length,inferred=state.batchRows.filter(r=>!r.match&&r.resolved).length;$('#batchSummary').textContent=rows.length?`結果 ${rows.length}${state.expectedTotal?` / 最多 ${state.expectedTotal}`:''}｜確認 ${matched}｜推定 ${inferred}｜候選 ${rows.length-matched-inferred}`:'';let h='<thead><tr><th>畫面#</th><th>狀態</th><th>姓名／候選</th><th>Rank</th><th>年齡</th><th>投／打</th><th>守位</th><th>成長</th><th>體力</th><th>球速</th><th>球威</th><th>控球</th><th>精神</th><th>守備</th><th>接球</th><th>臂力</th><th>傳球</th><th>技能</th><th>原型</th></tr></thead><tbody>';for(const r of rows){const p=batchDisplayPlayer(r),alts=(r.candidates||[]).filter(x=>x.p._uid!==p?._uid).slice(0,2),status=r.match?'確認':r.resolved?'推定':'候選',name=p?esc(p['名前']):'—',altText=alts.length?`<small class="candidate-note">候選：${alts.map(x=>esc(x.p['名前'])).join(' / ')}</small>`:'';h+=`<tr><td>${(r.firstIndex??0)+1}</td><td class="${r.match?'good':r.resolved?'estimate':'unresolved'}">${status}</td><td class="name" ${p?`data-uid="${esc(p._uid)}"`:''}>${name}${altText}</td><td class="rank">${esc(p?.['ランク']||'—')}</td><td>${esc(p?.['年齢']||r.parsed?.age||'—')}</td><td>${esc(p?.['投/打']||r.parsed?.hand||'—')}</td><td>${esc(p?._position||POSMAP[r.parsed?.pos]||'—')}</td><td>${esc(p?.['成長']||'—')}</td><td>${esc(p?.['体力']||'—')}</td><td>${esc(p?.['球速']||'—')}</td><td>${esc(p?.['球威']||'—')}</td><td>${esc(p?.['制球']||'—')}</td><td>${esc(p?.['精神']||'—')}</td><td>${esc(p?.['守備']||'—')}</td><td>${esc(p?.['捕球']||'—')}</td><td>${esc(p?.['肩力']||'—')}</td><td>${esc(p?.['送球']||'—')}</td><td>${esc([p?.['スキル1'],p?.['スキル2'],p?.['スキル3']].filter(Boolean).join('、')||'—')}</td><td>${esc(p?.['モデル']||'—')}</td></tr>`}h+='</tbody>';$('#batchTable').innerHTML=h;$('#batchTable').querySelectorAll('[data-uid]').forEach(td=>td.onclick=()=>openPlayer(td.dataset.uid))}
const batchSort=$('#batchSort');if(batchSort){batchSort.value=state.batchSort;batchSort.onchange=()=>{state.batchSort=batchSort.value;renderBatchResults()}}


let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
loadData().catch(e=>{$('#dataStatus').textContent='資料載入失敗：'+e.message;console.error(e)});