(function(){'use strict';
const state={players:[],_cvFonts:['sans-serif']};let cvTrialThreshold=106;
const POSMAP={投:'投手',捕:'捕手',一:'一壘手',二:'二壘手',三:'三壘手',遊:'游擊手',外:'外野手'};
function splitPlayerName(v){const a=String(v||'').trim().split(/\s+/).filter(Boolean);return{surname:a[0]||'',given:a.slice(1).join('')}}
function detectNameSeparator(canvas){const g=canvas.getContext('2d',{willReadFrequently:true}),id=g.getImageData(0,0,canvas.width,canvas.height).data,x0=Math.floor(canvas.width*.18),x1=Math.floor(canvas.width*.44),y0=Math.floor(canvas.height*.16),y1=Math.floor(canvas.height*.84),occ=[];for(let x=x0;x<x1;x++){let n=0;for(let y=y0;y<y1;y++){const i=(y*canvas.width+x)*4,l=id[i]*.299+id[i+1]*.587+id[i+2]*.114;if(l>178)n++}occ.push(n/Math.max(1,y1-y0))}let best=null,st=-1;for(let i=0;i<=occ.length;i++){const ok=i<occ.length&&occ[i]>.46;if(ok&&st<0)st=i;if((!ok||i===occ.length)&&st>=0){const en=i,w=en-st;if(w>=4&&(!best||w>best.w))best={a:x0+st,b:x0+en,w};st=-1}}return best?{left:best.a/canvas.width,right:best.b/canvas.width}:{left:.285,right:.325}}
function cvMaskRegion(src,rx0,rx1,threshold=108){const sx=Math.max(0,Math.floor(src.width*rx0)),ex=Math.min(src.width,Math.ceil(src.width*rx1)),sw=Math.max(1,ex-sx),g=src.getContext('2d',{willReadFrequently:true}),id=g.getImageData(sx,0,sw,src.height).data,pts=[];for(let y=0;y<src.height;y++)for(let x=0;x<sw;x++){const i=(y*sw+x)*4,l=id[i]*.299+id[i+1]*.587+id[i+2]*.114;if(l>threshold)pts.push([x,y])}if(!pts.length)return null;let minx=sw,miny=src.height,maxx=0,maxy=0;for(const [x,y] of pts){if(x<minx)minx=x;if(x>maxx)maxx=x;if(y<miny)miny=y;if(y>maxy)maxy=y}minx=Math.max(0,minx-1);miny=Math.max(0,miny-1);maxx=Math.min(sw-1,maxx+1);maxy=Math.min(src.height-1,maxy+1);const w=maxx-minx+1,h=maxy-miny+1,bits=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=((miny+y)*sw+(minx+x))*4,l=id[i]*.299+id[i+1]*.587+id[i+2]*.114;bits[y*w+x]=l>threshold?1:0}return{bits,w,h,splitCache:new Map(),ratio:w/Math.max(1,h)}}
function cvNormalizeCell(bits,w,h,size=20){let minx=w,miny=h,maxx=-1,maxy=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(bits[y*w+x]){if(x<minx)minx=x;if(x>maxx)maxx=x;if(y<miny)miny=y;if(y>maxy)maxy=y}const out=new Uint8Array(size*size);if(maxx<minx||maxy<miny)return{bits:out,w:size,h:size};const bw=maxx-minx+1,bh=maxy-miny+1,scale=Math.min((size-2)/bw,(size-2)/bh),dw=Math.max(1,Math.round(bw*scale)),dh=Math.max(1,Math.round(bh*scale)),ox=Math.floor((size-dw)/2),oy=Math.floor((size-dh)/2);for(let yy=0;yy<dh;yy++)for(let xx=0;xx<dw;xx++){const sx=minx+Math.min(bw-1,Math.floor(xx/Math.max(scale,.001))),sy=miny+Math.min(bh-1,Math.floor(yy/Math.max(scale,.001)));if(bits[sy*w+sx])out[(oy+yy)*size+ox+xx]=1}return{bits:out,w:size,h:size}}
function cvDescriptor(bm){return Array.from(bm.bits)}
function cvFeatureSimilarity(a,b){if(!a||!b||a.length!==b.length)return 0;let inter=0,A=0,B=0;for(let i=0;i<a.length;i++){inter+=a[i]&&b[i];A+=a[i];B+=b[i]}return(2*inter)/(A+B+1e-6)}
const cvGlyphTemplateCache=new Map();
function cvRenderedGlyphFeatures(ch){if(cvGlyphTemplateCache.has(ch))return cvGlyphTemplateCache.get(ch);const out=[];for(const family of state._cvFonts){const c=document.createElement('canvas');c.width=52;c.height=52;const g=c.getContext('2d',{willReadFrequently:true});g.fillStyle='#000';g.fillRect(0,0,52,52);g.fillStyle='#fff';g.textBaseline='middle';g.textAlign='center';g.font='700 36px '+family;g.fillText(ch,26,26);const id=g.getImageData(0,0,52,52).data,bits=new Uint8Array(52*52);for(let i=0,j=0;i<id.length;i+=4,j++)bits[j]=id[i]>80?1:0;out.push(cvDescriptor(cvNormalizeCell(bits,52,52,20)))}cvGlyphTemplateCache.set(ch,out);return out}
function cvSplitFeatures(target,count){count=Math.max(1,Math.min(12,count|0));if(!target)return[];if(target.splitCache.has(count))return target.splitCache.get(count);const out=[],step=target.w/count;for(let i=0;i<count;i++){const x0=Math.floor(i*step),x1=i===count-1?target.w:Math.floor((i+1)*step),w=Math.max(1,x1-x0),bits=new Uint8Array(w*target.h);for(let y=0;y<target.h;y++)for(let x=0;x<w;x++)bits[y*w+x]=target.bits[y*target.w+x0+x];out.push(cvDescriptor(cvNormalizeCell(bits,w,target.h,20)))}target.splitCache.set(count,out);return out}
function cvWordScore(target,word){const chars=[...String(word||'').replace(/\s+/g,'')];if(!target||!chars.length||chars.length>12)return 0;const tf=cvSplitFeatures(target,chars.length);let sum=0,min=1;for(let i=0;i<chars.length;i++){let best=0;for(const tpl of cvRenderedGlyphFeatures(chars[i]))best=Math.max(best,cvFeatureSimilarity(tf[i],tpl));sum+=best;if(best<min)min=best}const mean=sum/chars.length,expected=Math.max(.7,chars.length*.86),aspect=Math.exp(-Math.abs(Math.log(Math.max(.15,target.ratio)/expected))*.26);return(Math.max(0,mean*.78+min*.22))*aspect}
function cvCandidateMatch(canvas){const sep=detectNameSeparator(canvas),surnameTarget=cvMaskRegion(canvas,.115,Math.max(.18,sep.left-.008),cvTrialThreshold),givenTarget=cvMaskRegion(canvas,Math.min(.50,sep.right+.008),.575,cvTrialThreshold);if(!surnameTarget&&!givenTarget)return{candidates:[]};const s=surnameTarget?.ratio||0,g=givenTarget?.ratio||0,scache=new Map(),gcache=new Map(),score=(a,word,cache)=>{if(!a)return 0;if(cache.has(word))return cache.get(word);const v=cvWordScore(a,word);cache.set(word,v);return v};const start=performance.now();const list=state.players.map(p=>{const q=splitPlayerName(p['名前']);const ss=score(surnameTarget,q.surname,scache),gs=score(givenTarget,q.given,gcache),v=(ss*.46+gs*.54)/((surnameTarget?.46:0)+(givenTarget?.54:0)||1);return{p,score:v,ss,gs}}).sort((a,b)=>b.score-a.score);return{candidates:list.slice(0,6),all:list,ms:performance.now()-start,separator:sep}}
function rowCropsNew(im,file){const d=detectRows(im),out=[];for(let i=0;i<d.rows.length;i++){const x=d.panel.x,y=d.rows[i].start,w=Math.floor(Math.min(d.panel.w*.69,im.width-x)),h=d.rows[i].end-y;const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,x,y,w,h,0,0,w,h);out.push({canvas:c,file,row:i+1})}return out}
window.batchTestSetup=(players,th=106,family='sans-serif')=>{state.players=players;cvTrialThreshold=th;state._cvFonts=[family];cvGlyphTemplateCache.clear()};window.batchTestRows=rowCropsNew;window.batchTestScore=cvCandidateMatch;
function cvClassifyFinite(src,rx0,rx1,labels,threshold=108){const target=cvMaskRegion(src,rx0,rx1,threshold);if(!target)return{value:'',score:0,margin:0};const arr=labels.map(v=>({value:v,score:cvWordScore(target,v)})).sort((a,b)=>b.score-a.score),a=arr[0],b=arr[1];if(!a)return{value:'',score:0,margin:0};return{value:a.value,score:a.score,margin:a.score-(b?.score||0)}}
function cvTrialHand(row){return cvClassifyFinite(row,.78,.985,['右/右','右/左','左/左','左/右','右/両','左/両'],cvTrialThreshold)}
window.batchTrialHand=cvTrialHand;
function cvRowParts(row,th=126){const sep=detectNameSeparator(row);return[cvMaskRegion(row,.115,Math.max(.18,sep.left-.008),th),cvMaskRegion(row,Math.min(.5,sep.right+.008),.575,th)].map(b=>b?cvNormalizeCell(b.bits,b.w,b.h,32).bits:null)}
function cvRowSimilarity(a,b,th=126){const xs=cvRowParts(a,th),ys=cvRowParts(b,th);let z=0,n=0;for(let i=0;i<2;i++)if(xs[i]&&ys[i]){let D=0,X=0,Y=0;for(let j=0;j<xs[i].length;j++){const aa=xs[i][j],bb=ys[i][j];D+=aa*bb;X+=aa;Y+=bb}z+=2*D/(X+Y+1e-6);n++}return n?z/n:0}
window.batchRowSimilarity=cvRowSimilarity;window.cvRowParts=cvRowParts;

})();